################################################################################
# Makefile for building: A simple library for useful functions for analysis    #
################################################################################

include ../general.mk

####### Targets, add new objects here
TARGET_LIB    = libcana.so
LIB_OBJ_DIR   = obj
LIB_CLASSES   = canalib

LIB_OBJECTS   = $(addprefix $(LIB_OBJ_DIR)/, $(LIB_CLASSES:=.o))

include ../rules.mk
