################################################################################
# Makefile for building: A simple library for useful functions for analysis    #
################################################################################

include ../general.mk

####### Targets, add new objects here
TARGET_LIB    = libcana.so
OBJECTS_DIR   = obj
CXX_SOURCES   = cana_utils \
                cana_integrate

HEADER_FILES  = include/*

include ../rules.mk
