################################################################################
# Makefile for building: A configuration library for parsing strings           #
################################################################################

include ../general.mk

####### Targets, add new objects here
TARGET_LIB    = libprconf.so
OBJECTS_DIR   = obj
CXX_SOURCES   = ConfigValue \
                ConfigParser \
                ConfigObject \
                ConfigOption

HEADER_FILES  = include/*

include ../rules.mk
