################################################################################
# Makefile for building: A simple neural network for pattern recognition       #
################################################################################

include ../general.mk

####### Targets, add new objects here
TARGET_LIB    = libcneural.so
OBJECTS_DIR   = obj
CXX_SOURCES   = CNeuralNetwork \
                CNeuronLayer \
                CNeuron

HEADER_FILES  = include/*

include ../rules.mk
